### ISSUE TITLE
sway-msg may fail badly when current-directory doesn't exist anymore

### ISSUE THREAD

**Issue by nicolas-graves** [thblt/sway.el#9]
It's quite hard to understand where exactly things go wrong here. When I try to use `git send-email`, emacs + sway.el may fail badly (I have to restart-emacs). 

Some example : 
```
     git send-email --to="~abcdw/rde-devel@lists.sr.ht" --cc="ngraves@ngraves.fr" HEAD^
    --cover-letter
    /tmp/uwvTrfH_bX/0000-cover-letter.patch
    /tmp/uwvTrfH_bX/0001-rde-feature-org-Fix-org-id-locations-file.patch
    Refusing to send because the patch
            /tmp/uwvTrfH_bX/0000-cover-letter.patch
    has the template subject '*** SUBJECT HERE ***'. Pass --force if you really want to send.

    It opens the cover-letter patch in emacs BUT deletes the directory.
    So even if I try to save the file, I will get an annoying

    sway-msg: Setting current directory: Aucun fichier ou dossier de ce type, /tmp/uwvTrfH_bX/
```

So I guess it's something about `sway-msg` trying to open a buffer when the current directory doesn't exist anymore. Instead of discarding the buffer, it simply refuses to do anything (the minibuffer invocation fails). 

Will try to reproduce with emacs -Q and sway.el only later.

**Comment by nicolas-graves** [comment]
Just to add a little more detail: of course the original error comes from the fact that git send-email won't properly edit files and deletes the directory while the cover-letter patch is opened. It probably fails not here, but I think when the first buffer cover-letter is deleted, it tries to open the second patch buffer which doesn't exist anymore. 

Anyway, the error is not originating from sway.el, but the way it fails should be more graceful.

**Comment by thblt** [comment]
Thanks!

MRE:

(find-file "/does/not/exist/file")
In that buffer, eval:
(sway-msg nil "[con_id=16] focus;")

This should work.

Root issue is in `call-process`:

(let ((default-directory "/does/not/exist"))
  (call-process "echo"))

**Comment by nicolas-graves** [comment]
@thblt The straightforward solution seems to be to simply wrap the `call-process` call with `with-existing-directory`. 
My local repo is messed up, I won't make a patch but it's tested and works well. 
```
(with-current-buffer buffer
      (with-existing-directory
        (call-process sway-swaymsg-binary nil buffer nil message))
      (when (functionp handler)
        (prog2
            (goto-char (point-min))
            (funcall handler)
          (kill-buffer buffer))))
```

**Comment by thblt** [comment]
Should be good, please check with the original use case to confirm the issue is solved. Notice this change increases the minimal supported Emacs version to 28.1 (because `with-existing-directory`)
